/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EIOSIDFA_AUTODEFS_H
#define S3EIOSIDFA_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_IOSIDFA_NAME "s3eIOSIDFA"
#define S3E_EXT_IOSIDFA_HASH 0xf1c66af

#endif /* !S3EIOSIDFA_AUTODEFS_H */
