/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "s3eIOSIdentifiers.h"


// For MIPs (and WP8) platform we do not have asm code for stack switching 
// implemented. So we make LoaderCallStart call manually to set GlobalLock
#if defined __mips || defined S3E_ANDROID_X86 || (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP))
#define LOADER_CALL
#endif

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef    s3eBool(*s3eIOSIdentifiersIsIDFATrackingEnabled_t)();
typedef const char*(*s3eIOSIdentifiersGetIDFA_t)();
typedef const char*(*s3eIOSIdentifiersGetIDFV_t)();

/**
 * struct that gets filled in by s3eIOSIdentifiersRegister
 */
typedef struct s3eIOSIdentifiersFuncs
{
    s3eIOSIdentifiersIsIDFATrackingEnabled_t m_s3eIOSIdentifiersIsIDFATrackingEnabled;
    s3eIOSIdentifiersGetIDFA_t m_s3eIOSIdentifiersGetIDFA;
    s3eIOSIdentifiersGetIDFV_t m_s3eIOSIdentifiersGetIDFV;
} s3eIOSIdentifiersFuncs;

static s3eIOSIdentifiersFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x9c0bcfb1, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: s3eIOSIdentifiers");
            
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x9c0bcfb1, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eIOSIdentifiersAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eBool s3eIOSIdentifiersIsIDFATrackingEnabled()
{
    IwTrace(IOSIDENTIFIERS_VERBOSE, ("calling s3eIOSIdentifiers[0] func: s3eIOSIdentifiersIsIDFATrackingEnabled"));

    if (!_extLoad())
        return S3E_FALSE;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eBool ret = g_Ext.m_s3eIOSIdentifiersIsIDFATrackingEnabled();

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

const char* s3eIOSIdentifiersGetIDFA()
{
    IwTrace(IOSIDENTIFIERS_VERBOSE, ("calling s3eIOSIdentifiers[1] func: s3eIOSIdentifiersGetIDFA"));

    if (!_extLoad())
        return NULL;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    const char* ret = g_Ext.m_s3eIOSIdentifiersGetIDFA();

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

const char* s3eIOSIdentifiersGetIDFV()
{
    IwTrace(IOSIDENTIFIERS_VERBOSE, ("calling s3eIOSIdentifiers[2] func: s3eIOSIdentifiersGetIDFV"));

    if (!_extLoad())
        return NULL;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    const char* ret = g_Ext.m_s3eIOSIdentifiersGetIDFV();

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}
